export const fileMap: Record<string, string[]> = {
  "./examples": [
    "actions",
    "animation",
    "audio",
    "bugs",
    "cache",
    "camera",
    "components",
    "demoscene",
    "depth sorting",
    "display",
    "events",
    "fx",
    "game config",
    "game elements",
    "game objects",
    "games",
    "geom",
    "input",
    "loader",
    "math",
    "paths",
    "physics",
    "plugins",
    "pools",
    "renderer",
    "scalemanager",
    "scenes",
    "snapshot",
    "spine3",
    "spine4",
    "textures",
    "tilemap",
    "time",
    "transform",
    "tweens",
    "utils",
  ],
  "./examples/actions": [
    "align to base.js",
    "align to offset.js",
    "align to.js",
    "angle with step.js",
    "angle.js",
    "get first.js",
    "grid align animations.js",
    "grid align group.js",
    "grid align overlap.js",
    "grid align sprites.js",
    "inc x and y.js",
    "inc x.js",
    "inc y.js",
    "place on a circle multi.js",
    "place on a circle reversed.js",
    "place on circle.js",
    "place on ellipse.js",
    "place on line.js",
    "place on part of a circle.js",
    "place on rectangle shift.js",
    "place on rectangle.js",
    "place on triangle.js",
    "place sprites on circle.js",
    "place sprites on part of a circle.js",
    "random circle.js",
    "random ellipse.js",
    "random line.js",
    "random rectangle.js",
    "random triangle.js",
    "rotate around distance.js",
    "rotate around x y.js",
    "rotate around.js",
    "rotate container facing point.js",
    "set alpha.js",
    "set x y.js",
    "shift position snake.js",
    "shift position.js",
    "spread.js",
    "wrap in camera bounds.js",
    "wrap in rectangle with padding.js",
    "wrap in rectangle.js",
  ],
  "./examples/animation": [
    "60fps animation test.js",
    "add animation event.js",
    "add frames to existing animation.js",
    "animation from png sequence.js",
    "animation get progress.js",
    "animation repeat event.js",
    "aseprite animation.js",
    "chained animation.js",
    "create animation from canvas texture.js",
    "create animation from sprite sheet.js",
    "create animation from texture atlas.js",
    "create animation on sprite.js",
    "create animation without frame names.js",
    "create from sprite config.js",
    "cubes.js",
    "export json.js",
    "from animation json.js",
    "from json.js",
    "generate frame names.js",
    "generate frame numbers.js",
    "gif to animation.js",
    "hide on complete.js",
    "mixed animation.js",
    "multi atlas animation.js",
    "muybridge.js",
    "on complete event.js",
    "on repeat event.js",
    "on start event.js",
    "on stop event.js",
    "on update event.js",
    "pause all animations.js",
    "pause animation instances.js",
    "play after delay.js",
    "play after random delay.js",
    "play after repeat.js",
    "play animation with config.js",
    "random delay.js",
    "remove animation event.js",
    "reverse animation.js",
    "show animation play through.js",
    "show on start.js",
    "sprite animation events.js",
    "stagger play 1.js",
    "stagger play 2.js",
    "start from random frame.js",
    "tween timescale.js",
    "yoyo.js",
  ],
  "./examples/audio": ["HTML5 Audio", "No Audio", "SID", "Web Audio"],
  "./examples/audio/HTML5 Audio": [
    "Loop Delay.js",
    "Seek.js",
    "Volume Mute Rate Detune.js",
    "audiosprite.js",
    "basic playback and events.js",
    "disable pause on blur.js",
    "markers pause resume.js",
    "markers play.js",
    "play audio file.js",
    "play audio from child scene.js",
  ],
  "./examples/audio/No Audio": [
    "AudioSprite.js",
    "Basic Playback and Events.js",
    "Loop Delay.js",
    "Seek.js",
    "Volume Mute Rate Detune.js",
    "markers pause resume.js",
    "markers play.js",
  ],
  "./examples/audio/SID": ["c64 sid player.js"],
  "./examples/audio/Web Audio": [
    "AudioSprite.js",
    "Basic Playback and Events.js",
    "Loop Delay.js",
    "Seek.js",
    "Volume Mute Rate Detune.js",
    "markers pause resume.js",
    "markers play.js",
    "play audio file.js",
    "play audio from child scene.js",
    "play audio from file pack.js",
    "play movement sound.js",
    "play sound on keypress.js",
    "reuse audio context.js",
    "spatial audio move with player.js",
    "spatial with destination coordinates.js",
    "using same audio file.js",
  ],
  "./examples/bugs": [
    "0000 audio play.js",
    "0000 big load 1024 canvas.js",
    "0000 big load 1024.js",
    "0000 big load split.js",
    "0000 big load tiny.js",
    "0000 big load.js",
    "0000 blur fx.js",
    "0000 canvastexture resize.js",
    "0000 char index.js",
    "0000 container alpha.js",
    "0000 drag scale.js",
    "0000 dt mem.js",
    "0000 frame cycle.js",
    "0000 gfx rect.js",
    "0000 hex corners.js",
    "0000 hex to world.js",
    "0000 input.js",
    "0000 mask.js",
    "0000 move dom.js",
    "0000 move test.js",
    "0000 multi atlas complete.js",
    "0000 onupdate.js",
    "0000 put tile at.js",
    "0000 round pixels.js",
    "0000 rp test.js",
    "0000 rt mem.js",
    "4337 drag destroy.js",
    "4391 tilemap off.js",
    "4644 container.js",
    "4704 scene time.js",
    "4793 tween restart.js",
    "4878 audio mute.js",
    "4905 hit area debug.js",
    "4910 video oncomplete.js",
    "5222 points.js",
    "5399 resize mask.js",
    "5420 plugin.js",
    "5423 rt to shader.js",
    "5426 rt canvas alpha.js",
    "5429 stroke.js",
    "5441 poly bounds.js",
    "5445 rt snapshot.js",
    "5452 light fill.js",
    "5454 tween play.js",
    "5456 memory.js",
    "5464 scene restart.js",
    "5464 text.js",
    "5476 light depth.js",
    "5478 display none.js",
    "5483 layer input.js",
    "5489 container input.js",
    "5493 spine blue.js",
    "5494 iso cull.js",
    "5501 bitmap text.js",
    "5507 always enabled.js",
    "5508 input.js",
    "5509 rt tint.js",
    "5522 lights.js",
    "5538 dom input.js",
    "5538 ios input.js",
    "5563 fbo.js",
    "5570 mesh.js",
    "5571 line to line.js",
    "5572 ff audio.js",
    "5576 destroy group.js",
    "5592 pointer move.js",
    "5596 spine canvas.js",
    "5603 rt mac os.js",
    "5608 hex tile.js",
    "5617 debug 1.js",
    "5617 debug 2.js",
    "5617 push circle.js",
    "5627 spine mask.js",
    "5667 ios blend.js",
    "5680 anim delay.js",
    "5699 rend list.js",
    "5707 rt beyond canvas.js",
    "5720 fill.js",
    "5774 canvas.js",
    "5781 iso tile.js",
    "5802 geom post.js",
    "5803 update list.js",
    "5818 container update.js",
    "5830 rtl.js",
    "5846 container move.js",
    "5847 step particles.js",
    "5867 pointer out.js",
    "5873 video.js",
    "5883 layer camera.js",
    "5884 bounds.js",
    "5924 ios.js",
    "5939 snapshot fringe.js",
    "5952 game config.js",
    "5970 scale mode.js",
    "5974 headless.js",
    "5976 shape mask.js",
    "5986 tween.js",
    "6000 rt resize.js",
    "6001 json datakey.js",
    "6005 tween play.js",
    "6006 input over.js",
    "6009 tween update to.js",
    "6016 kill tweens nested.js",
    "6022 spine atlas.js",
    "6033 retina graphics.js",
    "6040 move scene.js",
    "6041 drag container.js",
    "6052 anim in container.js",
    "6057 rt frame.js",
    "6078 scene remove.js",
    "6091 go duplication.js",
    "6093 graphics canvas.js",
    "6097 render config.js",
    "6120 post fx.js",
    "6121 rtl.js",
    "6123 interactive load.js",
    "6126 physics light.js",
    "6133 zone angle.js",
    "6169 tween pause.js",
    "6173 kill tweens of.js",
    "6178 matter polygon.js",
    "6180 cam zoom snapshot.js",
    "6187 word wrap.js",
    "6188 map copy.js",
    "6253 tween restart.js",
    "6268 layer destroy.js",
    "6282 scene restart.js",
    "6283 ios16.js",
    "6293 physics.js",
    "6327 aseprite.js",
    "6362 spine atlas.js",
    "6367 text.js",
    "6380 spine.js",
    "6407 post fx mask.js",
    "6411 rt resize.js",
    "6425 particles.js",
    "6434 aseprite.js",
    "6440 clear fx.js",
    "6503 resize fx.js",
    "6515 particle multi.js",
    "6527 mask resize 2.js",
    "6527 mask resize.js",
    "6604 line width.js",
    "6614 atlas prefix.js",
    "6615 rt fill.js",
    "6616 rt stamp.js",
    "6674 resize.js",
    "6677 bloom.js",
    "6681 fx frame.js",
    "6682 dyn can.js",
    "6691 trim tile.js",
    "6724 layer.js",
    "polygon rays.js",
  ],
  "./examples/cache": ["json file.js", "text file.js", "xml file.js"],
  "./examples/camera": [
    "16 camera shader test.js",
    "16 camera test.js",
    "32 camera test.js",
    "add camera on click.js",
    "background color interpolate.js",
    "background color.js",
    "basics.js",
    "bounds at zero.js",
    "camera alpha.js",
    "camera blur shader.js",
    "camera center on.js",
    "camera effect callbacks.js",
    "camera effects.js",
    "camera fade in and out.js",
    "camera fade out and in.js",
    "camera filter.js",
    "cameras from state config.js",
    "change camera shader.js",
    "cross scene object placement.js",
    "fade.js",
    "fixed to camera.js",
    "flash.js",
    "follow offset.js",
    "follow sprite small bounds.js",
    "follow sprite with deadzone.js",
    "follow sprite.js",
    "follow user controlled sprite.js",
    "follow zoom tilemap.js",
    "follow zoom.js",
    "game shader test 1.js",
    "game shader test 2.js",
    "game shader test 3.js",
    "get world point.js",
    "graphics landscape.js",
    "ignore container.js",
    "ignore gameobjects in containers.js",
    "ignore gameobjects.js",
    "ignore group children.js",
    "ignore.js",
    "minimap camera.js",
    "move camera with keys.js",
    "multi camera",
    "multiple cameras.js",
    "origin.js",
    "overlap.js",
    "pan to.js",
    "remove camera on click.js",
    "render to texture shader 2.js",
    "render to texture shader 3.js",
    "render to texture shader 4.js",
    "render to texture shader 5.js",
    "render to texture shader 6.js",
    "render to texture shader.js",
    "render to texture.js",
    "rotate camera.js",
    "round pixels.js",
    "scroll view.js",
    "select shader test.js",
    "set bounds.js",
    "set scroll factor.js",
    "set small bounds.js",
    "set viewport.js",
    "shader multi cam test.js",
    "shake.js",
    "single small camera.js",
    "tile map with camera shake.js",
    "world camera.js",
    "world coordinate from another scene.js",
    "world view.js",
    "zoom to.js",
  ],
  "./examples/camera/multi camera": [
    "Controller.js",
    "DemoA.js",
    "DemoB.js",
    "DemoC.js",
    "DemoD.js",
    "Obj3D.js",
    "boot.json",
    "game.js",
  ],
  "./examples/components": ["data"],
  "./examples/components/data": [
    "change data event.js",
    "data values.js",
    "get and set data values.js",
    "query data.js",
    "set data event.js",
    "set multiple values.js",
    "store scene data.js",
  ],
  "./examples/demoscene": [
    "_wip",
    "chunky raster bars.js",
    "raster carpet.js",
    "raster wave.js",
    "vertical raster wave.js",
  ],
  "./examples/demoscene/_wip": ["birdy nam nam.js"],
  "./examples/depth sorting": [
    "ball mesh depth sort.js",
    "bring to top.js",
    "get top object.js",
    "isometric blocks.js",
    "isometric map.js",
    "remove from display list.js",
    "sprite depth index.js",
    "z index.js",
  ],
  "./examples/display": [
    "align",
    "alpha",
    "blend modes",
    "color",
    "masks",
    "shaders",
    "tint",
  ],
  "./examples/display/align": [
    "in bottom center.js",
    "in bottom left.js",
    "in bottom right.js",
    "in center.js",
    "in left center.js",
    "in right center.js",
    "in top center.js",
    "in top left.js",
    "in top right.js",
  ],
  "./examples/display/alpha": [
    "bottom alpha.js",
    "single alpha.js",
    "top alpha.js",
    "top left alpha.js",
    "tween alpha.js",
  ],
  "./examples/display/blend modes": [
    "blend mode tester.js",
    "circle cut out.js",
    "custom blend mode with graphics.js",
    "custom blend mode.js",
    "custom separate blend mode.js",
    "difference.js",
    "graphics blend mode.js",
    "overlay.js",
    "particle.js",
  ],
  "./examples/display/color": [
    "brighten.js",
    "darken.js",
    "hex to color.js",
    "integer to color.js",
    "lighten.js",
    "random color.js",
    "random gray.js",
    "rgb to color.js",
  ],
  "./examples/display/masks": [
    "dynamic texture as bitmap mask.js",
    "geometry mask from shape.js",
    "graphics bitmap mask.js",
    "nested bitmap mask.js",
    "shared bitmap mask.js",
  ],
  "./examples/display/shaders": [
    "shader test 1.js",
    "shader test 2.js",
    "shader test 3.js",
    "shader test 4.js",
    "shader test 5.js",
    "shader test 6.js",
    "shader test 7.js",
    "shader test 8.js",
  ],
  "./examples/display/tint": [
    "atlas frame tint.js",
    "corner tint.js",
    "multiple images.js",
    "per vertex tint.js",
    "pixel wave.js",
    "rainbow text.js",
    "rasters.js",
    "single color tint.js",
    "text tint.js",
    "tile sprite tint.js",
    "tint and alpha.js",
    "tint fill effect.js",
    "tint fill.js",
    "tween tint.js",
  ],
  "./examples/events": [
    "create event emitter.js",
    "emit scene event.js",
    "emit using symbols.js",
    "event arguments.js",
    "game object events.js",
    "listen to game object event.js",
    "once event.js",
    "turn off anonymous event handler.js",
    "turn off event handler.js",
  ],
  "./examples/fx": [
    "barrel",
    "bloom",
    "blur",
    "bokeh",
    "colormatrix",
    "displacement",
    "glow",
    "gradient",
    "pixelate",
    "shadow",
    "shine",
    "vignette",
    "wipe",
  ],
  "./examples/fx/barrel": [
    "barrel fx.js",
    "barrel sprite fx.js",
    "barrel squish fx.js",
    "barrel text.js",
  ],
  "./examples/fx/bloom": ["destroy planet bloom fx.js"],
  "./examples/fx/blur": ["blur fx.js", "container blur.js"],
  "./examples/fx/bokeh": ["particle bokeh.js", "tiltshift camera.js"],
  "./examples/fx/colormatrix": [
    "colormatrix fx.js",
    "colormatrix hue shift fx.js",
  ],
  "./examples/fx/displacement": [
    "displacement circles fx.js",
    "displacement fx.js",
    "displacement skull fx.js",
  ],
  "./examples/fx/glow": [
    "double glow post fx.js",
    "glow bitmaptext.js",
    "glow fx.js",
    "glow graphics.js",
    "glow post fx.js",
    "glow rope fx.js",
    "glow text.js",
  ],
  "./examples/fx/gradient": [
    "chunky gradient.js",
    "gradient fx.js",
    "gradient mouse twist fx.js",
    "tilemap gradient.js",
  ],
  "./examples/fx/pixelate": [
    "pixelate amount.js",
    "pixelate fx.js",
    "pixelate sprite fx.js",
    "pixelate transition scene.js",
  ],
  "./examples/fx/shadow": ["shadow fx.js", "text shadow fx.js"],
  "./examples/fx/shine": [
    "blitter shine.js",
    "shine fx.js",
    "tilemap layer shine.js",
  ],
  "./examples/fx/vignette": [
    "vignette camera.js",
    "vignette radius.js",
    "vignette sprite fx.js",
    "vignette strength.js",
    "vignette xy.js",
  ],
  "./examples/fx/wipe": [
    "reveal bottom to top.js",
    "reveal left to right.js",
    "reveal right to left.js",
    "reveal text.js",
    "reveal top to bottom.js",
    "wipe bottom to top.js",
    "wipe left to right.js",
    "wipe right to left.js",
    "wipe to a scene.js",
    "wipe to pointer.js",
    "wipe top to bottom.js",
    "wipe width.js",
  ],
  "./examples/game config": [
    "background color.js",
    "banner colors.js",
    "clear before render.js",
    "custom canvas.js",
    "custom webgl canvas.js",
    "custom webgl2 canvas.js",
    "game destroy with multi scenes.js",
    "game destroy.js",
    "game rng.js",
    "game title.js",
    "game url.js",
    "game version.js",
    "headless renderer.js",
    "hide banner.js",
    "hide phaser from banner.js",
    "multiple game instances.js",
    "pixel art mode.js",
    "round pixels.js",
    "transparent.js",
  ],
  "./examples/game elements": ["dice.js"],
  "./examples/game objects": [
    "bitmaptext",
    "blitter",
    "container",
    "display list",
    "dom element",
    "extern",
    "graphics",
    "group",
    "images",
    "layer",
    "lights",
    "mesh",
    "nine slice",
    "particle emitter",
    "plane",
    "render texture",
    "rope",
    "shaders",
    "shapes",
    "sprites",
    "tests",
    "text",
    "tile sprite",
    "video",
  ],
  "./examples/game objects/bitmaptext": ["dynamic", "retro font", "static"],
  "./examples/game objects/bitmaptext/dynamic": [
    "canvas text.js",
    "display callback index effect.js",
    "display callback rotation effect.js",
    "display callback scale effect.js",
    "display callback wibble effect.js",
    "text follow path.js",
    "tinted text.js",
    "vertical scroller.js",
  ],
  "./examples/game objects/bitmaptext/retro font": [
    "retro text 1.js",
    "retro text 2.js",
    "retro text mega scroll.js",
    "retro text scroll callback.js",
    "retro text scroll.js",
    "scrolling retro text.js",
    "tinted retro text.js",
  ],
  "./examples/game objects/bitmaptext/static": [
    "bitmaptext blend mode.js",
    "bitmaptext origin and scale.js",
    "bitmaptext rotation.js",
    "bitmaptext scale.js",
    "bitmaptext-atlas.js",
    "bitmaptext-canvas.js",
    "bitmaptext.js",
    "change font size.js",
    "change font.js",
    "drop shadow.js",
    "get bitmaptext bounds.js",
    "get text size multiline.js",
    "get text size scaled.js",
    "get text size.js",
    "large-text.js",
    "max width change content.js",
    "max width.js",
    "multi line alignment.js",
    "multi line.js",
    "origin and scale.js",
    "padding.js",
    "text origin.js",
    "tinted text.js",
    "width and height.js",
  ],
  "./examples/game objects/blitter": [
    "benchmark test 1.js",
    "benchmark test 2.js",
    "benchmark test 3.js",
    "blitter alpha.js",
    "blitter camera test canvas.js",
    "blitter camera test.js",
    "blitter global alpha.js",
    "bob frame object.js",
    "bobs using a multi atlas.js",
    "canvas benchmark 1.js",
    "create from callback.js",
    "multiple atlas frame bobs.js",
    "multiple bobs.js",
    "single atlas frame bob.js",
    "single image bob.js",
    "tween test 1.js",
    "twist scroller.js",
  ],
  "./examples/game objects/container": [
    "add array of sprites at index.js",
    "add array of sprites to container.js",
    "add emitter to container.js",
    "add sprite to container.js",
    "add tilesprite to container.js",
    "animation test.js",
    "arcade physics body test.js",
    "arcade physics sprite test.js",
    "camera transform test.js",
    "child blend mode.js",
    "child order.js",
    "container alpha.js",
    "container and camera zoom.js",
    "container and child input.js",
    "container as mask.js",
    "container depth.js",
    "container hitarea from size.js",
    "container hitarea.js",
    "container ik.js",
    "container input test.js",
    "container mask.js",
    "container placement.js",
    "container scrollfactor.js",
    "create container.js",
    "draggable container.js",
    "get bounds test 1.js",
    "get child world position.js",
    "girl body sprites.js",
    "input overlap test.js",
    "matter physics body test camera.js",
    "matter physics body test.js",
    "matter physics sprite test.js",
    "multi camera input test.js",
    "multi container depth test.js",
    "multiple non exclusive containers.js",
    "nested container input test.js",
    "nested container visibility.js",
    "nested get bounds test.js",
    "nested input test.js",
    "non exclusive containers.js",
    "parent matrix.js",
    "rotated input test.js",
    "rotation.js",
    "scaled input test.js",
    "text and sprite test.js",
    "twirl 1.js",
    "twirl 2.js",
    "twirl 3.js",
    "twirl 4.js",
    "twirl 5.js",
    "twirl 6.js",
  ],
  "./examples/game objects/display list": [
    "add to container.js",
    "add to display list.js",
    "display list to container.js",
    "display list to layer.js",
    "move container.js",
    "move layer.js",
    "remove from display list.js",
    "swap container.js",
  ],
  "./examples/game objects/dom element": [
    "blend mode.js",
    "css style object.js",
    "css text.js",
    "cursors test.js",
    "div depth.js",
    "div position test 1.js",
    "div position test 2.js",
    "div position test 3.js",
    "div position test 4.js",
    "div position test 5.js",
    "form input.js",
    "input test.js",
    "move camera.js",
    "physics element.js",
    "rotate3d.js",
    "skew.js",
    "sleeping scene test.js",
    "using a div.js",
    "video element.js",
  ],
  "./examples/game objects/extern": ["threejs cube.js"],
  "./examples/game objects/graphics": [
    "Graphics Rendering.js",
    "Line Rendering.js",
    "_wip",
    "arc stroke.js",
    "arc.js",
    "atari lines.js",
    "circle overlap.js",
    "circles test.js",
    "fill rect.js",
    "fill rounded rectangle.js",
    "generate texture test.js",
    "generate texture to blitter.js",
    "generate texture to sprite.js",
    "generate texture to tilesprite.js",
    "graphics in a container.js",
    "graphics styles.js",
    "health bars demo.js",
    "line thickness.js",
    "many stars.js",
    "mouse trail.js",
    "multiple cameras.js",
    "multiple graphic instances.js",
    "multiple stroke rects.js",
    "obj scene.js",
    "pacman arc chomp chomp.js",
    "pacman arc.js",
    "phaser logo 3d.js",
    "phaser logo shift.js",
    "phaser logo.js",
    "primitive types.js",
    "primitives",
    "rect test.js",
    "spinning cube.js",
    "star shape.js",
    "stroke circle.js",
    "stroke path.js",
    "stroke rect.js",
    "stroke rounded rectangle.js",
    "stroke triangle.js",
    "teapot.js",
    "trace.js",
    "transform.js",
  ],
  "./examples/game objects/graphics/_wip": [
    "circle spin.js",
    "draw triangles.js",
    "obj viewer.js",
    "obj world cam.js",
    "obj world.js",
    "single obj viewer.js",
  ],
  "./examples/game objects/graphics/primitives": [
    "arc filled.js",
    "arc gradient filled.js",
    "arc stroked.js",
    "line between.js",
    "line filled.js",
    "line gradient stroked.js",
    "path gradient filled.js",
    "path stroked.js",
    "rectangle filled texture.js",
    "rectangle filled.js",
    "rectangle gradient filled.js",
    "rectangle stroked.js",
    "scene stack test.js",
    "split path filled.js",
    "triangle gradient filled.js",
    "triangle gradient stroked.js",
    "triangle stroked.js",
  ],
  "./examples/game objects/group": [
    "create child.js",
    "create invaders.js",
    "create multiple keys.js",
    "create multiple.js",
    "destroy child.js",
    "multiple adds.js",
    "random frame.js",
    "set rotation.js",
    "set scale.js",
    "set x.js",
    "set xy.js",
    "set y.js",
    "shuffle.js",
    "sprite pool.js",
    "swirl.js",
  ],
  "./examples/game objects/images": [
    "blend test.js",
    "custom game object.js",
    "custom image class ES6.js",
    "custom image class.js",
    "destroy an image.js",
    "flip.js",
    "get bounds.js",
    "image alpha.js",
    "image bounds.js",
    "image edge points.js",
    "image offset.js",
    "image rotation.js",
    "make image from config.js",
    "multiple alpha.js",
    "multiple image rotation.js",
    "single image.js",
  ],
  "./examples/game objects/layer": [
    "add sprite to layer.js",
    "create layer.js",
    "depth sort layer children.js",
    "layer post pipeline.js",
    "layer with bitmap mask.js",
    "layer with geometry mask.js",
    "move between layers.js",
    "nested layers.js",
  ],
  "./examples/game objects/lights": [
    "bitmap text light.js",
    "blitter light.js",
    "change max lights.js",
    "change scene.js",
    "create point light.js",
    "draw light.js",
    "graveyard.js",
    "light culling.js",
    "light follow pointer.js",
    "mesh light.js",
    "particles light.js",
    "point lights.js",
    "render texture light.js",
    "rotated sprite.js",
    "single light.js",
    "spotlight.js",
    "sprite sheet light.js",
    "text light.js",
    "tilemap layer.js",
    "tilesprite light.js",
    "zoom point light.js",
  ],
  "./examples/game objects/mesh": [
    "_wip",
    "mesh drag input.js",
    "mesh from array.js",
    "mesh from generate grid.js",
    "mesh from obj.js",
    "mesh input.js",
    "mesh pointer input.js",
    "race track.js",
  ],
  "./examples/game objects/mesh/_wip": [
    "draw mesh.js",
    "filled torus.js",
    "mesh battleship.js",
    "mesh deer.js",
    "mesh elephant.js",
    "mesh gun.js",
    "mesh scale.js",
    "mesh scene.js",
    "mesh snowman.js",
    "mesh squirrel.js",
    "mesh test.js",
    "mesh tree.js",
  ],
  "./examples/game objects/nine slice": [
    "3 slice button.js",
    "create nine slice.js",
    "interactive button.js",
    "nine slice panel.js",
    "nine slice vs scaling.js",
    "progress bar.js",
    "stress test.js",
    "texture packer nine slice.js",
  ],
  "./examples/game objects/particle emitter": [
    "_wip",
    "add emit zone.js",
    "bring to top.js",
    "change emitter tint.js",
    "custom callback.js",
    "direct value.js",
    "emit at pointer.js",
    "emit zone loop.js",
    "emitter alpha.js",
    "emitter duration.js",
    "emitter events.js",
    "emitter zone total.js",
    "explode emitter.js",
    "fire effects.js",
    "get emitter bounds.js",
    "get particle bounds.js",
    "gravity processor.js",
    "hold particle.js",
    "interpolation ease.js",
    "min max.js",
    "move to dynamic.js",
    "move to.js",
    "multiple death zones.js",
    "onEmit and onUpdate.js",
    "particle bounds.js",
    "particle overlap.js",
    "particle physics body overlap.js",
    "random array.js",
    "random object.js",
    "random tint.js",
    "set emitter zone by instance.js",
    "set emitter zone.js",
    "sort order.js",
    "start end ease.js",
    "start end random.js",
    "start end.js",
    "stepped emitter with yoyo.js",
    "stepped emitter.js",
    "stop after.js",
    "tween alpha.js",
    "tween speed x.js",
    "tween speed y.js",
    "tween speed.js",
    "tween xy.js",
    "view bounds.js",
  ],
  "./examples/game objects/particle emitter/_wip": [
    "acceleration.js",
    "angled emitter.js",
    "animated particles.js",
    "animation.js",
    "camera test.js",
    "change emitter order.js",
    "christmas tree.js",
    "collide emitter bounds sides.js",
    "create emitter from JSON.js",
    "create emitter from config 2.js",
    "create emitter from config 3.js",
    "create emitter from config 4.js",
    "create emitter from config 5.js",
    "create emitter from config.js",
    "create emitter.js",
    "custom particles.js",
    "death zone custom.js",
    "death zone follow mouse.js",
    "death zone from arcade body.js",
    "death zone on enter.js",
    "death zone on leave.js",
    "digital rain.js",
    "double acceleration.js",
    "dynamic emitter config property.js",
    "edge zone custom.js",
    "edge zone from curve.js",
    "edge zone speed.js",
    "edge zone.js",
    "electric 2.js",
    "electric.js",
    "emit from manager.js",
    "emit from shape.js",
    "emit from sprites.js",
    "emit from texture.js",
    "emitter bounds.js",
    "emitter follow sprite.js",
    "emitter2",
    "explode test.js",
    "fire max 10 particles.js",
    "fireballs.js",
    "fireworks.js",
    "follow sprite.js",
    "frame cycle.js",
    "gravity well.js",
    "manager transform.js",
    "mouse trail.js",
    "move to center.js",
    "move to.js",
    "multiple emitters.js",
    "parallax.js",
    "particle editor.js",
    "particle processor.js",
    "particles on a moving curve.js",
    "particles on a path.js",
    "quantity limit.js",
    "random emit zone custom.js",
    "random emit zone.js",
    "rotating line.js",
    "scale emitter.js",
    "stepped angle.js",
    "stepped lifespan.js",
    "stepped position and speed.js",
    "stepped position.js",
    "stepped speed.js",
    "test new ops.js",
    "tint.js",
    "y position range.js",
  ],
  "./examples/game objects/particle emitter/_wip/emitter2": [
    "test 1.js",
    "test anims.js",
    "test color.js",
    "test fire color.js",
    "test frames.js",
    "test processor.js",
    "test set config.js",
    "test set texture.js",
  ],
  "./examples/game objects/plane": [
    "animated sprite plane.js",
    "checkerboard plane.js",
    "click plane.js",
    "create plane from atlas frame.js",
    "create plane.js",
    "plane drag input.js",
    "plane pop-up effect.js",
    "plane with bitmap mask.js",
    "plane with normal map.js",
    "tile plane texture.js",
    "uv scale plane texture.js",
    "uv scroll plane texture.js",
    "walls.js",
  ],
  "./examples/game objects/render texture": [
    "_wip",
    "atlas frame to render texture.js",
    "batch draw frame.js",
    "batch draw sprite.js",
    "blitter to render texture.js",
    "brute force.js",
    "change frame.js",
    "container to render texture.js",
    "destroy game with render texture.js",
    "destroy render texture.js",
    "draw game objects to render texture.js",
    "draw on texture.js",
    "dynamic bitmap text to render texture.js",
    "dynamic tilemap to render texture.js",
    "erase part of render texture canvas.js",
    "erase part of render texture.js",
    "frame fill.js",
    "graphics to render texture.js",
    "group to render texture.js",
    "paint interpolated shadow.js",
    "paint interpolated.js",
    "paint tinted.js",
    "paint.js",
    "particle emitter to render texture.js",
    "pixel art test.js",
    "render texture as a mask.js",
    "render texture larger than camera.js",
    "render texture to render texture.js",
    "resize render texture.js",
    "resize rendertexture.js",
    "save texture.js",
    "scene to render texture quad.js",
    "scene to render texture with crop.js",
    "scene to render texture.js",
    "scratch.js",
    "shape to render texture.js",
    "sprite to render texture.js",
    "static bitmap text to render texture.js",
    "static tilemap to render texture.js",
    "text to render texture.js",
    "texture key to render texture.js",
    "trail.js",
    "trail2.js",
    "transform draw.js",
  ],
  "./examples/game objects/render texture/_wip": [
    "explosion.js",
    "fireball.js",
    "nine slice frame.js",
    "sparks.js",
  ],
  "./examples/game objects/rope": [
    "animated rope.js",
    "draw rope gradient.js",
    "draw rope.js",
    "flip rope xy.js",
    "horizontal rope.js",
    "rope as a mask.js",
    "rope with a mask.js",
    "rope with shader texture.js",
    "single alpha rope.js",
    "split alpha rope.js",
    "vertex tint rope.js",
    "vertical rope.js",
  ],
  "./examples/game objects/shaders": [
    "basic texture shader.js",
    "buffer a.js",
    "buffer b.js",
    "change shader texture.js",
    "load shader.js",
    "sandbox.js",
    "save shader as texture.js",
    "set shader uniform.js",
    "shader arcade physics.js",
    "shader as a mask.js",
    "shader bundle.js",
    "shader mass texture test.js",
    "shader transforms.js",
    "shader using a dynamic texture.js",
    "shader using an updating dynamic texture.js",
    "using a shader as a buffer.js",
  ],
  "./examples/game objects/shapes": [
    "arc.js",
    "blend modes.js",
    "circle.js",
    "curve.js",
    "draw.js",
    "ellipse.js",
    "grid.js",
    "iso birdie.js",
    "iso box.js",
    "iso draw.js",
    "iso image.js",
    "iso landscape.js",
    "iso triangle.js",
    "line.js",
    "polygon contains.js",
    "polygon with matter physics.js",
    "polygon.js",
    "rectangle with arcade physics.js",
    "rectangle.js",
    "spline.js",
    "stacker es6.js",
    "stacker.js",
    "star.js",
    "triangle.js",
  ],
  "./examples/game objects/sprites": [
    "create from config.js",
    "custom sprite class ES6.js",
    "moving sprite.js",
    "multiple sprites.js",
    "rotate around a sprite.js",
    "single sprite.js",
    "sprite alpha.js",
    "sprite rotation.js",
    "to json.js",
  ],
  "./examples/game objects/tests": [
    "dynamic bitmap text.js",
    "image.js",
    "single tilesprite.js",
    "static bitmap text.js",
    "text.js",
    "tilesprite.js",
  ],
  "./examples/game objects/text": [
    "align text.js",
    "basic text.js",
    "change text.js",
    "create from config.js",
    "custom webfont.js",
    "emojis.js",
    "google webfont.js",
    "italic text.js",
    "line spacing.js",
    "multi line text with alignment.js",
    "multi line text.js",
    "padding from config.js",
    "right origin.js",
    "right to left text.js",
    "set test string.js",
    "shadow stroke styles.js",
    "simple text button.js",
    "speech bubble.js",
    "tests",
    "text bounds.js",
    "text gradient.js",
    "text key.js",
    "text metrics.js",
    "text origin.js",
    "text padding.js",
    "text with fallback font.js",
    "to json.js",
    "word wrap by callback.js",
    "word wrap by width.js",
  ],
  "./examples/game objects/text/tests": ["word wrap.js"],
  "./examples/game objects/tile sprite": [
    "Atlas - Canvas.js",
    "Atlas.js",
    "Example - Canvas.js",
    "Example 2 - Canvas.js",
    "Example 2.js",
    "Example.js",
    "change frame and size.js",
    "change frame.js",
    "change single frame.js",
    "create from frame.js",
    "flipped.js",
    "tilesprite pixel art test.js",
  ],
  "./examples/game objects/video": [
    "change video source.js",
    "load video from url.js",
    "loop video.js",
    "multiple video instances.js",
    "multiple videos.js",
    "on complete event.js",
    "play video.js",
    "stream video from webcam.js",
    "transparent video.js",
    "video as shader texture.js",
    "video controls.js",
    "video set current time.js",
    "video snapshot area.js",
    "video snapshot.js",
    "video to sprites.js",
    "video transition.js",
  ],
  "./examples/games": [
    "avoid the germs",
    "bank panic",
    "breakout",
    "card memory",
    "coin clicker",
    "emoji match",
    "firstgame",
    "flood fill",
    "minesweeper",
    "sliding puzzle",
    "snake",
    "snowmen attack",
    "stacker",
    "tom",
  ],
  "./examples/games/avoid the germs": [
    "Boot.js",
    "Game.js",
    "Germ.js",
    "Germs.js",
    "MainMenu.js",
    "Pickups.js",
    "Player.js",
    "Preloader.js",
    "boot.json",
    "main.js",
  ],
  "./examples/games/bank panic": [
    "Boot.js",
    "Door.js",
    "Game.js",
    "MainMenu.js",
    "Preloader.js",
    "boot.json",
    "main.js",
  ],
  "./examples/games/breakout": ["breakout.js"],
  "./examples/games/card memory": [
    "Play.js",
    "Preloader.js",
    "boot.json",
    "createCard.js",
    "main.js",
  ],
  "./examples/games/coin clicker": [
    "Boot.js",
    "ClickerGame.js",
    "GameOver.js",
    "MainMenu.js",
    "Preloader.js",
    "main.js",
  ],
  "./examples/games/emoji match": [
    "Boot.js",
    "Game.js",
    "MainMenu.js",
    "Preloader.js",
    "boot.json",
    "main.js",
  ],
  "./examples/games/firstgame": [
    "assets",
    "part1.html",
    "part1.js",
    "part10.html",
    "part10.js",
    "part2.html",
    "part2.js",
    "part3.html",
    "part3.js",
    "part4.html",
    "part4.js",
    "part5.html",
    "part5.js",
    "part6.html",
    "part6.js",
    "part7.html",
    "part7.js",
    "part8.html",
    "part8.js",
    "part9.html",
    "part9.js",
    "phaser3-tutorial-src.zip",
  ],
  "./examples/games/firstgame/assets": [
    "bomb.png",
    "dude.png",
    "platform.png",
    "sky.png",
    "star.png",
  ],
  "./examples/games/flood fill": ["flood-fill.js"],
  "./examples/games/minesweeper": ["minesweeper.js"],
  "./examples/games/sliding puzzle": [
    "Game.js",
    "MainMenu.js",
    "Preloader.js",
    "ShinePostFX.js",
    "WipePostFX.js",
    "boot.json",
    "main.js",
  ],
  "./examples/games/snake": [
    "_part8.js",
    "part1.js",
    "part2.js",
    "part3.js",
    "part4.js",
    "part5.js",
    "part6.js",
    "part7.js",
  ],
  "./examples/games/snowmen attack": [
    "Boot.js",
    "EnemySnowball.js",
    "Game.js",
    "MainMenu.js",
    "Player.js",
    "PlayerSnowball.js",
    "Preloader.js",
    "Snowman.js",
    "Track.js",
    "boot.json",
    "main.js",
  ],
  "./examples/games/stacker": ["stacker.js"],
  "./examples/games/tom": [
    "Menu.js",
    "Play.js",
    "Preloader.js",
    "TomBombs.js",
    "Tomato.js",
    "TomatoItem.js",
    "UI.js",
    "boot.json",
    "main.js",
  ],
  "./examples/geom": [
    "circle",
    "ellipse",
    "intersects",
    "line",
    "point",
    "polygon",
    "rectangle",
    "triangle",
  ],
  "./examples/geom/circle": [
    "area.js",
    "change size.js",
    "circumference point.js",
    "circumference.js",
    "clone.js",
    "contains point.js",
    "contains rect.js",
    "contains.js",
    "copy from.js",
    "create.js",
    "equals.js",
    "get bounds.js",
    "get point at.js",
    "get points.js",
    "get random point.js",
    "is empty.js",
    "offset point.js",
    "offset.js",
    "properties.js",
    "set empty.js",
    "set position.js",
    "set to.js",
  ],
  "./examples/geom/ellipse": [
    "adjust size.js",
    "area.js",
    "circumference point.js",
    "circumference.js",
    "clone.js",
    "contains point.js",
    "contains rect.js",
    "contains.js",
    "copy from.js",
    "create ellipse.js",
    "equals.js",
    "get bounds.js",
    "get major radius.js",
    "get minor radius.js",
    "get point at.js",
    "get points.js",
    "get random point.js",
    "is empty.js",
    "move ellipse.js",
    "offset point.js",
    "offset.js",
    "properties.js",
    "set empty.js",
    "set position.js",
    "set size.js",
    "set to.js",
  ],
  "./examples/geom/intersects": [
    "circle to circle.js",
    "get rectangle intersection.js",
    "line to circle.js",
    "line to line.js",
    "line to rectangle.js",
    "point to line segment.js",
    "point to line.js",
    "rectangle to circle.js",
    "rectangle to rectangle.js",
    "rectangle to triangle.js",
    "rectangle to values.js",
    "triangle to circle.js",
    "triangle to line.js",
    "triangle to triangle.js",
  ],
  "./examples/geom/line": [
    "angle.js",
    "bresenham points.js",
    "center on.js",
    "clone.js",
    "copy from.js",
    "create.js",
    "equals.js",
    "get eased points.js",
    "get mid point.js",
    "get normal.js",
    "get point ab.js",
    "get point at.js",
    "get points.js",
    "get random point.js",
    "height.js",
    "inverse line.js",
    "length.js",
    "normal angle.js",
    "normal xy.js",
    "offset.js",
    "perp slope.js",
    "point on line.js",
    "properties.js",
    "reflect angle.js",
    "rotate around point.js",
    "rotate around xy.js",
    "rotate.js",
    "set to angle.js",
    "set to.js",
    "slope.js",
    "width.js",
  ],
  "./examples/geom/point": [
    "ceil.js",
    "clone.js",
    "copy from.js",
    "create.js",
    "cross.js",
    "equals.js",
    "floor.js",
    "get centroid.js",
    "get magnitude sq.js",
    "get magnitude.js",
    "get rectangle from points.js",
    "interpolate.js",
    "invert.js",
    "negative 2.js",
    "negative.js",
    "project unit.js",
    "project.js",
    "set to.js",
  ],
  "./examples/geom/polygon": [
    "area.js",
    "basic polygon.js",
    "clone.js",
    "complex polygon.js",
    "contains point.js",
    "contains.js",
    "get aabb.js",
    "get number array.js",
    "get points.js",
    "polygon edge rays.js",
    "set to.js",
  ],
  "./examples/geom/rectangle": [
    "area.js",
    "ceil all.js",
    "ceil.js",
    "center on.js",
    "clone.js",
    "contains point.js",
    "contains rect.js",
    "contains.js",
    "copy from.js",
    "create.js",
    "decompose.js",
    "deflate.js",
    "equals.js",
    "fit inside.js",
    "fit outside.js",
    "floor all.js",
    "floor.js",
    "from points.js",
    "get aspect ratio.js",
    "get center.js",
    "get line.js",
    "get point.js",
    "get points.js",
    "get random point outside.js",
    "get random point.js",
    "get size.js",
    "inflate.js",
    "intersection.js",
    "is empty.js",
    "marching ants.js",
    "merge points.js",
    "merge rect.js",
    "merge xy.js",
    "offset point.js",
    "offset.js",
    "overlaps.js",
    "perimeter point.js",
    "perimeter.js",
    "properties.js",
    "scale.js",
    "set empty.js",
    "set position.js",
    "set size.js",
    "set to.js",
    "sprite to perimeter.js",
    "union.js",
  ],
  "./examples/geom/triangle": [
    "area.js",
    "bottom.js",
    "build equilateral.js",
    "build from polygon.js",
    "build right.js",
    "center on.js",
    "centroid.js",
    "circumcenter.js",
    "circumcircle.js",
    "clone.js",
    "contains array.js",
    "contains point.js",
    "contains.js",
    "copy from.js",
    "create triangle.js",
    "decompose.js",
    "equals.js",
    "get line.js",
    "get point.js",
    "get points.js",
    "get random point.js",
    "in center.js",
    "left.js",
    "offset.js",
    "perimeter.js",
    "random.js",
    "right.js",
    "rotate around point.js",
    "rotate around xy.js",
    "rotate from center.js",
    "set to.js",
    "top.js",
  ],
  "./examples/input": [
    "camera",
    "cursors",
    "dom events",
    "dragging",
    "game object",
    "gamepad",
    "keyboard",
    "mouse",
    "multitouch",
    "pixel perfect",
    "pointer",
    "zones",
  ],
  "./examples/input/camera": [
    "camera container ignore.js",
    "camera ignore.js",
    "graphics contains.js",
    "large world high res.js",
    "multi cam sprite.js",
    "stacked camera test.js",
    "world coordinates.js",
  ],
  "./examples/input/cursors": [
    "custom cursor.js",
    "cute cursor.js",
    "sc2 cursors.js",
  ],
  "./examples/input/dom events": [
    "on canvas out.js",
    "pointer button status.js",
  ],
  "./examples/input/dragging": [
    "bring dragged item to top.js",
    "camera move and rotate.js",
    "drag container.js",
    "drag distance threshold.js",
    "drag horizontally.js",
    "drag on a fixed axis.js",
    "drag time threshold.js",
    "drag vertically.js",
    "drag with multiple scenes.js",
    "enable for drag test 2.js",
    "enable for drag.js",
    "multi camera stack of cards.js",
    "multiple draggables.js",
    "multiple rotated and scaled.js",
    "multiple scene drag.js",
    "retain index after drag.js",
    "rotated and scaled.js",
    "scale during drag.js",
    "scroll factor drag.js",
    "scrolling text box.js",
    "snap to grid on drag.js",
    "stack of cards.js",
  ],
  "./examples/input/game object": [
    "change sprite hitarea size.js",
    "custom shape hit area.js",
    "debug hitarea.js",
    "destroy sprite on down event.js",
    "graphics object example.js",
    "multiple down.js",
    "multiple over out.js",
    "multiple up.js",
    "on down event.js",
    "on move event.js",
    "on up event.js",
    "over and out events.js",
    "select and deselect.js",
    "sprite example.js",
    "tilesprite on down.js",
    "top only over out events.js",
    "top only up down events.js",
    "use hand cursor.js",
    "world game objects.js",
  ],
  "./examples/input/gamepad": [
    "_twin stick shooter.js",
    "axes.js",
    "gamepad across scenes.js",
    "gamepad debug.js",
    "move sprite.js",
    "select gamepad.js",
  ],
  "./examples/input/keyboard": [
    "add key using string.js",
    "add key.js",
    "add single key.js",
    "create key combo.js",
    "cross scene keys.js",
    "cursor keys.js",
    "cursors time.js",
    "enter name.js",
    "global keydown event.js",
    "just down.js",
    "key combo max key delay.js",
    "key down delay.js",
    "key down duration.js",
    "key modifier.js",
    "keydown multi scene test.js",
    "keydown.js",
    "konami code key combo.js",
    "numpad.js",
    "reset key combo on match.js",
    "retro leaderboard.js",
    "single keydown event.js",
    "text entry.js",
  ],
  "./examples/input/mouse": [
    "_pointer lock 3d rotate.js",
    "check button released.js",
    "circle hit area.js",
    "click sprite.js",
    "ellipse hit area.js",
    "mass scrolling sprite test no cull.js",
    "mass scrolling sprite test.js",
    "mass sprite test.js",
    "mouse down.js",
    "mouse wheel over gameobject.js",
    "mouse wheel.js",
    "move event.js",
    "origin tests.js",
    "over and out events.js",
    "pointer lock.js",
    "poll always.js",
    "poll only on move.js",
    "polygon hit area.js",
    "right mouse button.js",
    "shape hit tests.js",
    "single sprite.js",
    "text input test.js",
    "top only over and out events.js",
    "top only up and down events.js",
    "top only.js",
    "triangle hit area.js",
  ],
  "./examples/input/multitouch": [
    "multi down test.js",
    "multi drag.js",
    "multi over test.js",
    "multi touch test.js",
    "two touch inputs.js",
  ],
  "./examples/input/pixel perfect": [
    "atlas frame.js",
    "image with lots of alpha.js",
    "large trimmed atlas frame.js",
    "on down.js",
    "on drag.js",
    "on move.js",
    "transformed.js",
  ],
  "./examples/input/pointer": [
    "cards.js",
    "down event.js",
    "drag rectangle.js",
    "draw sprites.js",
    "event list.js",
    "external link.js",
    "move event.js",
    "multi camera cards.js",
    "multiple scene down event.js",
    "pointer buttons debug.js",
    "pointer buttons.js",
    "pointer debug.js",
  ],
  "./examples/input/zones": [
    "basic input zone.js",
    "circular drop zone.js",
    "drop zone.js",
    "resize zone.js",
    "sprite drop zone.js",
  ],
  "./examples/loader": [
    "animation json",
    "audio",
    "base64",
    "binary",
    "bitmap text",
    "file pack",
    "game load config.js",
    "html",
    "image",
    "load config tests.js",
    "load from 404.js",
    "loader events",
    "plugin",
    "scene",
    "scene payload",
    "script",
    "sprite sheet",
    "svg",
    "texture atlas json",
    "texture atlas multi",
    "texture atlas unity",
    "texture atlas xml",
    "tile maps",
  ],
  "./examples/loader/animation json": ["load animation json.js"],
  "./examples/loader/audio": [
    "load audio sprite resources.js",
    "load audio sprite.js",
    "load audio stream.js",
    "load audio.js",
    "load html5 audio.js",
  ],
  "./examples/loader/base64": [
    "base64 bitmap font.js",
    "base64 image.js",
    "base64 texture atlas.js",
    "bitmap text.js",
  ],
  "./examples/loader/binary": [
    "load binary data from object.js",
    "load binary data parse after load.js",
    "load binary data.js",
  ],
  "./examples/loader/bitmap text": [
    "load bitmap text from pack.js",
    "load bitmap text.js",
  ],
  "./examples/loader/file pack": [
    "load file pack from json.js",
    "load file pack test 2.js",
    "load file pack test 3.js",
    "load file pack test 4.js",
    "load file pack test 5.js",
    "load file pack.js",
  ],
  "./examples/loader/html": ["load html to texture.js"],
  "./examples/loader/image": [
    "load image from object.js",
    "load image on click.js",
    "load image.js",
    "load normal map from object.js",
    "load normal map with light.js",
    "load normal map.js",
    "load webp.js",
  ],
  "./examples/loader/loader events": [
    "add files during load.js",
    "destroy game during load.js",
    "display file as loaded.js",
    "file complete event with key.js",
    "file complete event.js",
    "file progress event.js",
    "load 200 image files.js",
    "load from external url.js",
    "load progress.js",
    "multi file progress event.js",
    "play animation during load.js",
    "start loader manually.js",
    "test loading files already loaded.js",
  ],
  "./examples/loader/plugin": ["load plugin.js"],
  "./examples/loader/scene": ["load scene.js"],
  "./examples/loader/scene payload": ["scene files payload.js"],
  "./examples/loader/script": ["load script.js"],
  "./examples/loader/sprite sheet": [
    "load sprite sheet from object array.js",
    "load sprite sheet from object.js",
    "load sprite sheet from scene payload.js",
    "load sprite sheet.js",
  ],
  "./examples/loader/svg": [
    "load svg with fixed size.js",
    "load svg with scale.js",
    "load svg.js",
  ],
  "./examples/loader/texture atlas json": [
    "get atlas custom frame data.js",
    "get atlas meta data.js",
    "load atlas with local json.js",
    "load remove and reload atlas.js",
    "load texture atlas from object.js",
    "load texture atlas from pack.js",
    "load texture atlas from payload.js",
    "load texture atlas with normal map from object.js",
    "load texture atlas with normal map.js",
    "load texture atlas.js",
    "mixed json test.js",
  ],
  "./examples/loader/texture atlas multi": [
    "load multi texture atlas with normal maps.js",
    "load multi texture atlas.js",
    "load webp multi texture atlas.js",
  ],
  "./examples/loader/texture atlas unity": [
    "load unity spritesheet animation.js",
    "load unity spritesheet.js",
  ],
  "./examples/loader/texture atlas xml": ["load xml texture atlas.js"],
  "./examples/loader/tile maps": [
    "load tile map from local json.js",
    "load tile map json from object.js",
    "load tile map json from scene payload.js",
    "load tile map json with normal map.js",
    "load tile map json.js",
  ],
  "./examples/math": ["distance", "vec2"],
  "./examples/math/distance": [
    "distance between points.js",
    "distance.js",
    "get chebyshev distance.js",
    "snake distance.js",
  ],
  "./examples/math/vec2": [
    "add.js",
    "divide.js",
    "dot.js",
    "multiply.js",
    "normalize.js",
    "perp.js",
    "rperp.js",
    "set magnitude.js",
    "subtract.js",
  ],
  "./examples/paths": [
    "_path editor",
    "all types.js",
    "circle loop path.js",
    "circle path.js",
    "complex path bounds.js",
    "curves",
    "followers",
    "landscape path.js",
    "line to ellipse.js",
    "move to.js",
    "path add line curve.js",
    "path bounds.js",
    "path line and bezier.js",
    "simple path.js",
    "velocity from tangent vectors.js",
    "zig zag path.js",
  ],
  "./examples/paths/_path editor": ["Controller.js", "boot.json", "main.js"],
  "./examples/paths/curves": [
    "cubic bezier bounds.js",
    "cubic bezier curve debug.js",
    "cubic bezier curve.js",
    "drag cubic bezier curve.js",
    "drag ellipse curve.js",
    "drag line curve.js",
    "drag quadratic bezier curve.js",
    "drag spline curve.js",
    "ellipse curve bounds.js",
    "ellipse curve.js",
    "get distance on line curve.js",
    "get point from spline curve.js",
    "get points on cubic bezier curve.js",
    "get points on line curve.js",
    "get spaced points on cubic bezier curve.js",
    "get spaced points on line curve.js",
    "get spaced points vs get points.js",
    "get tangent vectors on cubic bezier curve.js",
    "line curve bounds.js",
    "line curve.js",
    "point types.js",
    "quadratic bezier curve.js",
    "rectangle spline intersection.js",
    "spline between points.js",
    "spline builder.js",
    "spline curve bounds.js",
    "spline curve distance points.js",
    "spline curve from array.js",
    "spline curve.js",
  ],
  "./examples/paths/followers": [
    "basic follower.js",
    "change path.js",
    "leave path.js",
    "mass followers.js",
    "multi curve path.js",
    "path from json all types.js",
    "path from json.js",
    "pause and resume.js",
    "rotate to path.js",
    "rotation offset.js",
    "sparkle trail.js",
    "start at.js",
    "wave path.js",
    "yoyo follower.js",
  ],
  "./examples/physics": ["arcade", "matterjs", "multi"],
  "./examples/physics/arcade": [
    "100 world bodies.js",
    "1000 world bodies.js",
    "10000 world bodies.js",
    "40000 world bodies.js",
    "500 colliding bodies.js",
    "accelerate to.js",
    "add body to shape.js",
    "add body to tilesprite.js",
    "angle from velocity.js",
    "angular acceleration.js",
    "angular velocity.js",
    "apply force.js",
    "asteroids movement.js",
    "basic platform.js",
    "blocked faces.js",
    "blocked touching and embedded.js",
    "body controls.js",
    "body follow path.js",
    "body on a path.js",
    "body push blocks.js",
    "bounce test.js",
    "bullets group.js",
    "circular body.js",
    "circular collisions 2.js",
    "circular collisions 3.js",
    "circular collisions.js",
    "closest furthest.js",
    "collide event.js",
    "collider 1.js",
    "collider process callback.js",
    "collision direction.js",
    "collision filter.js",
    "custom bounds.js",
    "custom debug colors.js",
    "custom separate.js",
    "custom update.js",
    "custom world bounds.js",
    "destroy body.js",
    "direct control follow mouse.js",
    "direct control follow path.js",
    "direct control platforms.js",
    "direct control.js",
    "disable collider.js",
    "drag on both axes.js",
    "drag scalar.js",
    "drag with damping on both axes.js",
    "drag with damping.js",
    "drag.js",
    "draggable body.js",
    "dragon movement.js",
    "extending arcade sprite.js",
    "final delta.js",
    "fps test.js",
    "friction.js",
    "get bodies within circle.js",
    "get bodies within rectangle.js",
    "gravity.js",
    "group set velocity x.js",
    "group set velocity y.js",
    "group vs group.js",
    "group vs self.js",
    "group world bounds event.js",
    "immovable body.js",
    "interpolate velocity 2.js",
    "interpolate velocity.js",
    "larger bounding box.js",
    "mass collision test.js",
    "mass debug 2.js",
    "mass debug.js",
    "mass.js",
    "max speed.js",
    "move and stop at position.js",
    "move to pointer.js",
    "move to position by duration.js",
    "move to.js",
    "non pushable bodies.js",
    "overlap collider.js",
    "overlap event.js",
    "overlap process callback 2.js",
    "overlap process callback.js",
    "overlap zone static body.js",
    "overlap zone.js",
    "physics body without sprite.js",
    "pushable body debug 1.js",
    "pushable body debug 2.js",
    "racecar.js",
    "random velocity.js",
    "recycle physics body.js",
    "remove collider.js",
    "restart physics scene.js",
    "rolling body.js",
    "rotate to pointer.js",
    "rtree test.js",
    "scene config.js",
    "set world bounds.js",
    "simple body.js",
    "simple group.js",
    "smaller bounding box.js",
    "smooth stop.js",
    "space battle.js",
    "space.js",
    "sprite follow physics body.js",
    "sprite follow physics sprite.js",
    "sprite overlap group.js",
    "sprite vs group.js",
    "sprite vs immovable.js",
    "sprite vs multiple groups.js",
    "sprite vs sprite.js",
    "static body update.js",
    "static body.js",
    "static group.js",
    "sticky platform.js",
    "topdown shooter average focus.js",
    "topdown shooter combat mechanics.js",
    "topdown shooter player focus.js",
    "topdown shooter target focus.js",
    "touching faces.js",
    "trick platforms.js",
    "tween body.js",
    "tween velocity 2.js",
    "tween velocity.js",
    "using collide directly.js",
    "variable step.js",
    "velocity from angle 2.js",
    "velocity from angle.js",
    "vertical friction.js",
    "world bounds event custom.js",
    "world bounds event.js",
    "world controls.js",
    "world step event.js",
    "wrap group.js",
    "wrap sprite.js",
  ],
  "./examples/physics/matterjs": [
    "100 world bodies.js",
    "add body to bitmap text.js",
    "add body to text.js",
    "add body to tilesprite.js",
    "add body to world.js",
    "advanced shape creation.js",
    "attractors.js",
    "balls.js",
    "basic constraint.js",
    "body follow path.js",
    "body scale.js",
    "body to json.js",
    "body velocity.js",
    "bridge.js",
    "bullet pool.js",
    "chain.js",
    "chamfer body.js",
    "circle body.js",
    "circle stack.js",
    "circular body.js",
    "cloth.js",
    "collision event.js",
    "collision filter.js",
    "collision group.js",
    "compound body from physics editor.js",
    "compound body.js",
    "compound sensors.js",
    "container collision.js",
    "create sensor.js",
    "debug options.js",
    "destroy body.js",
    "drag filter with pointer.js",
    "drag through balls.js",
    "drag with pointer.js",
    "draw chain.js",
    "draw smoother stiff line.js",
    "draw stiff line.js",
    "draw triangles.js",
    "fixed rotation.js",
    "get bodies below point.js",
    "get shape bounds.js",
    "ignore gravity.js",
    "increase body scale.js",
    "is point within body.js",
    "mixed bodies.js",
    "move body with cursors.js",
    "multiple physics scenes.js",
    "no gravity.js",
    "offset body.js",
    "pachinko.js",
    "particles follow body.js",
    "physics editor.js",
    "polygon body.js",
    "rectangle body.js",
    "restart physics scene.js",
    "rotate body with cursors.js",
    "scene restart.js",
    "scene transition.js",
    "simple body.js",
    "sleep events.js",
    "snake.js",
    "thrust.js",
    "top down car body.js",
    "trapezoid body.js",
    "vertices body.js",
    "wrap plugin.js",
    "wrecking ball.js",
  ],
  "./examples/physics/multi": ["arcade and matter.js"],
  "./examples/plugins": [
    "add global plugin.js",
    "add scene plugin in config.js",
    "custom file type.js",
    "custom game object.js",
    "destroy game with plugin.js",
    "global plugin test 1.js",
    "global scene plugin.js",
    "install global plugin at runtime.js",
    "load plugin test 1.js",
    "load plugin test 2.js",
    "load scene plugin test 1.js",
    "load scene plugin test 2.js",
    "multiple global plugin instances.js",
    "scene plugin test 1.js",
    "scene plugin test 2.js",
    "scene plugin test 3.js",
    "start and stop a plugin.js",
  ],
  "./examples/pools": [
    "bullets.js",
    "create pool.js",
    "max size.js",
    "multi pools.js",
    "pool using a custom class.js",
    "seeded pool.js",
  ],
  "./examples/renderer": [
    "32 texture test.js",
    "batch size.js",
    "batch test.js",
    "bend pipeline.js",
    "color post fx pipeline.js",
    "container pipeline.js",
    "custom pipeline multi texture es6.js",
    "custom pipeline multi texture.js",
    "custom pipeline single texture es6.js",
    "custom pipeline single texture.js",
    "custom post fx pipeline.js",
    "grayscale pipeline added locally.js",
    "grayscale pipeline.js",
    "hue rotation pipeline.js",
    "multi color pipeline.js",
    "set pipeline data.js",
    "sprite test.js",
    "swirl sprite fx pipeline.js",
    "webgl debug.js",
    "webgl info.js",
  ],
  "./examples/scalemanager": [
    "_fit hi-res.js",
    "envelop min max.js",
    "envelop.js",
    "fit and snap.js",
    "fit min max.js",
    "fit running game.js",
    "fit with auto center.js",
    "fit.js",
    "full screen game.js",
    "height controls width.js",
    "manually resize with zoom.js",
    "manually resize.js",
    "mobile game example.js",
    "no scale with auto center.js",
    "no scale.js",
    "orientation check.js",
    "resize and fit.js",
    "resize min max.js",
    "resize on click.js",
    "resize.js",
    "width controls height.js",
    "world input.js",
    "zoom manual resize.js",
    "zoom with fit.js",
    "zoom with no scale.js",
  ],
  "./examples/scenes": [
    "add scene after game.js",
    "add scene from another scene.js",
    "boot data.js",
    "bring to top.js",
    "call function in another scene es6.js",
    "call function in another scene.js",
    "change scene from create es6.js",
    "change scene from create.js",
    "change scene from objects.js",
    "changing large scene.js",
    "changing scene es6.js",
    "changing scene.js",
    "copies of the same scene.js",
    "drag scenes demo.js",
    "extend scene from object.js",
    "external scene",
    "launch parallel scene.js",
    "move down list.js",
    "move up list.js",
    "moving scenes demo",
    "multi demo",
    "multiple scenes from classes.js",
    "multiple scenes from instances.js",
    "multiple scenes from objects.js",
    "multiple scenes with multiple cameras.js",
    "parallel scenes.js",
    "passing data to a scene.js",
    "pause and resume.js",
    "registry data exchange es6.js",
    "registry data exchange.js",
    "restart a scene.js",
    "scene add manual start.js",
    "scene add.js",
    "scene config object.js",
    "scene files payload.js",
    "scene from class.js",
    "scene from es6 class.js",
    "scene from function.js",
    "scene from instance.js",
    "scene from object.js",
    "scene injection map utf8.js",
    "scene injection map.js",
    "send to back.js",
    "sleep and wake.js",
    "sub game demo",
    "swap position.js",
    "swapping scenes.js",
    "test plugin.js",
    "transition test 1.js",
    "transition test 2.js",
    "tutorial",
    "ui scene es6.js",
    "ui scene.js",
  ],
  "./examples/scenes/external scene": ["Controller.js", "Demo.js", "boot.json"],
  "./examples/scenes/moving scenes demo": [
    "Controller.js",
    "SceneA.js",
    "SceneB.js",
    "SceneC.js",
    "SceneD.js",
    "SceneE.js",
    "SceneF.js",
    "boot.json",
    "main.js",
  ],
  "./examples/scenes/multi demo": [
    "Boing.js",
    "Clock.js",
    "Controller.js",
    "Eyes.js",
    "Invaders.js",
    "Juggler.js",
    "Stars.js",
    "boot.json",
    "main.js",
  ],
  "./examples/scenes/sub game demo": [
    "Preloader.js",
    "SubGame.js",
    "WorldMap.js",
    "boot.json",
    "main.js",
  ],
  "./examples/scenes/tutorial": [
    "change scene order.js",
    "scene controller.js",
    "scene order.js",
  ],
  "./examples/snapshot": [
    "snapshot area.js",
    "snapshot game.js",
    "snapshot pixel.js",
    "snapshot to base64.js",
  ],
  "./examples/spine3": [
    "add hit area.js",
    "add spine object to group.js",
    "alpha test.js",
    "arcade physics spine body.js",
    "basic spineboy.js",
    "batch test.js",
    "blend mode test.js",
    "camera pipeline test.js",
    "canvas test 1.js",
    "container batch test pre35.js",
    "container batch test.js",
    "control bones.js",
    "destroy test.js",
    "draw debug bounds.js",
    "extend spine gameobject.js",
    "extended class.js",
    "image changes.js",
    "invisible test with spine containers.js",
    "invisible test.js",
    "last visible.js",
    "owl.js",
    "spine inside container.js",
    "spine parallel scene test.js",
    "spine preloader test.js",
    "spine rotation test.js",
    "spine scene test.js",
    "spine set depth test.js",
    "spine to render texture.js",
    "webgl test 1.js",
    "webgl test 2.js",
    "webgl test 3.js",
    "webgl test 4.js",
    "webgl test 5.js",
  ],
  "./examples/spine4": [
    "add hit area.js",
    "add spine object to group.js",
    "alpha test.js",
    "arcade physics spine body.js",
    "basic spineboy.js",
    "batch test.js",
    "blend mode test.js",
    "camera pipeline test.js",
    "canvas test 1.js",
    "container batch test pre35.js",
    "container batch test.js",
    "control bones.js",
    "destroy test.js",
    "draw debug bounds.js",
    "extend spine gameobject.js",
    "extended class.js",
    "image changes.js",
    "invisible test with spine containers.js",
    "invisible test.js",
    "last visible.js",
    "owl.js",
    "spine inside container.js",
    "spine parallel scene test.js",
    "spine preloader test.js",
    "spine rotation test.js",
    "spine scene test.js",
    "spine set depth test.js",
    "spine to render texture.js",
    "webgl test 1.js",
    "webgl test 2.js",
    "webgl test 3.js",
    "webgl test 4.js",
    "webgl test 5.js",
  ],
  "./examples/textures": [
    "avif test.js",
    "batch texture.js",
    "canvas textures",
    "compressed multi texture atlas.js",
    "compressed texture atlas from file config.js",
    "compressed texture atlas from file pack.js",
    "compressed texture atlas.js",
    "compressed texture from file config.js",
    "compressed texture from file pack.js",
    "compressed texture.js",
    "crop animated sprite.js",
    "crop multi frames.js",
    "crop render texture.js",
    "crop text.js",
    "crop texture atlas frame flip.js",
    "crop texture atlas frame trimmed flip.js",
    "crop texture atlas frame trimmed.js",
    "crop texture atlas frame.js",
    "crop texture image flip.js",
    "crop texture image scaled.js",
    "crop texture image.js",
    "crop tilesprite.js",
    "dynamic textures",
    "edit texture hue shift.js",
    "edit texture silhouette.js",
    "frames from single atlas.js",
    "generate more textures.js",
    "generate texture.js",
    "get pixel dynamic.js",
    "get pixel from image.js",
    "get pixels.js",
    "multi atlas.js",
    "set mipmap filter.js",
    "sprite sheet from atlas.js",
    "sprite sheet.js",
    "sprite using tilemap texture.js",
    "text texture.js",
    "texture from base64.js",
    "texture packer atlas.js",
    "trimmed frame from multi atlas.js",
    "trimmed frame from single atlas.js",
  ],
  "./examples/textures/canvas textures": [
    "canvas texture composite op.js",
    "canvas texture rotation.js",
    "create canvas.js",
    "dwitter",
  ],
  "./examples/textures/canvas textures/dwitter": [
    "5475.js",
    "5479.js",
    "5500.js",
    "test.js",
  ],
  "./examples/textures/dynamic textures": [
    "copy image.js",
    "create dynamic texture.js",
    "dynamic texture camera test.js",
    "get pixel from dynamic texture.js",
    "masked sprite to dynamic texture.js",
    "multiple dynamic textures.js",
    "nine slice dynamic texture.js",
  ],
  "./examples/tilemap": [
    "base tile size.js",
    "collision",
    "copy tiles.js",
    "create from array.js",
    "create from objects.js",
    "create from tiles.js",
    "creating blank layers.js",
    "csv map.js",
    "danger.js",
    "debug colliding tiles.js",
    "dungeon generator.js",
    "endless map.js",
    "fill tiles.js",
    "get chebyshev distance.js",
    "get tiles in shape.js",
    "grid movement.js",
    "isometric",
    "layer size.js",
    "layer transform.js",
    "light map.js",
    "map vs layer with multiple layers.js",
    "map vs layer with one layer.js",
    "mario map scroller.js",
    "mouse wheel zoom.js",
    "multi camera map.js",
    "multiple tilesets.js",
    "paint tiles.js",
    "pixel art test.js",
    "put tiles.js",
    "randomize tiles.js",
    "replace tiles.js",
    "set colliding by collision data.js",
    "set colliding by property.js",
    "set colliding tiles.js",
    "set map size.js",
    "shuffle tiles.js",
    "snake distance.js",
    "swap tiles.js",
    "switching tilesets.js",
    "tests",
    "tile draw order.js",
    "tile overlap.js",
    "tile properties.js",
    "tiled  multi tileset.js",
    "tiled json map.js",
    "tilelayer pipeline.js",
    "tileset collision shapes.js",
    "tileset with spacing.js",
    "tint tiles.js",
    "weighted randomize.js",
    "zoom.js",
  ],
  "./examples/tilemap/collision": [
    "csv map arcade physics.js",
    "custom collide call.js",
    "matter destroy tile bodies.js",
    "matter detect collision with tile.js",
    "matter ghost collisions.js",
    "matter platformer modify map.js",
    "matter platformer with wall jumping.js",
    "matter.js",
    "multiple tile sizes.js",
    "simple map.js",
    "tile callbacks.js",
    "tilemap spotlight.js",
  ],
  "./examples/tilemap/isometric": [
    "create isometric manually.js",
    "hexagonal test.js",
    "isometric test.js",
  ],
  "./examples/tilemap/tests": [
    "semi automated tests.js",
    "visual culling check.js",
    "visual face test.js",
    "visual flipping test.js",
    "visual tile bleed test.js",
    "visual tile coords test.js",
    "visual worldxy test.js",
  ],
  "./examples/time": [
    "clock.js",
    "draw clocks.js",
    "looped event.js",
    "multiple timers.js",
    "pause and resume.js",
    "remove timer event.js",
    "repeat count.js",
    "reuse a timer event.js",
    "start at.js",
    "time scale.js",
    "timeline",
    "timer event.js",
    "timestep",
  ],
  "./examples/time/timeline": [
    "add event in.js",
    "create timeline.js",
    "from times.js",
    "play timeline on click.js",
    "repeat timeline.js",
    "run timed events.js",
    "set action.js",
    "sound action.js",
    "timeline event.js",
    "tween action.js",
  ],
  "./examples/time/timestep": [
    "delta history.js",
    "split timestep.js",
    "ticker loop.js",
    "variable smooth step.js",
    "world time.js",
  ],
  "./examples/transform": [
    "_wip",
    "angle.js",
    "display size.js",
    "flip x.js",
    "flip y.js",
    "originX.js",
    "originXY.js",
    "originY.js",
    "position.js",
    "rotation and origin.js",
    "rotation.js",
    "scaleX.js",
    "scaleXY.js",
    "scaleY.js",
  ],
  "./examples/transform/_wip": [
    "has point.js",
    "ik test.js",
    "position update.js",
    "scale update.js",
  ],
  "./examples/tweens": [
    "ball circle.js",
    "callbacks.js",
    "chains",
    "change texture after scale.js",
    "change texture.js",
    "checkerboard 1.js",
    "checkerboard 2.js",
    "checkerboard 3.js",
    "checkerboard rotate.js",
    "counter tween.js",
    "delay function.js",
    "eases",
    "flip x.js",
    "flip y.js",
    "global time scale.js",
    "loop.js",
    "remove tween.js",
    "seek to point in tween.js",
    "sprite angle between.js",
    "stagger delay.js",
    "stagger showcase.js",
    "tween gauge.js",
    "tween sprite angle.js",
    "tween text size.js",
  ],
  "./examples/tweens/chains": [
    "basic tween chain.js",
    "bat tween.js",
    "chest sequence.js",
    "multi target chain.js",
  ],
  "./examples/tweens/eases": [
    "back graph.js",
    "back.js",
    "bounce graph.js",
    "bounce.js",
    "circular graph.js",
    "circular.js",
    "cubic graph.js",
    "cubic.js",
    "ease mixer.js",
    "exponential graph.js",
    "exponential.js",
    "linear.js",
    "quad graph.js",
    "quad.js",
    "quartic graph.js",
    "quartic.js",
    "quintic graph.js",
    "quintic.js",
    "sine graph.js",
    "sine.js",
  ],
  "./examples/utils": ["array", "rbush", "size"],
  "./examples/utils/array": [
    "bring to top.js",
    "range.js",
    "reverse matrix columns.js",
    "reverse matrix rows.js",
    "rotate matrix 180.js",
    "rotate matrix left.js",
    "rotate matrix right.js",
    "rotate matrix.js",
    "translate matrix.js",
    "transpose matrix.js",
  ],
  "./examples/utils/rbush": ["rbush 1.js", "rbush 2.js"],
  "./examples/utils/size": [
    "aspect mode envelop.js",
    "aspect mode fit.js",
    "aspect mode height controls width.js",
    "aspect mode none.js",
    "aspect mode width controls height.js",
    "max size.js",
    "min max size.js",
    "min size.js",
    "snap child.js",
  ],
};
